### ISSUE TITLE
Create nn_lib git submodule

### ISSUE THREAD

**Issue by nhanvtran** [hls-fpga-machine-learning/HLS4ML#4]
Can we create a common git submodule to serve all purposes?

**Comment by ejk43** [comment]
Seems to be going pretty well to work inside this framework so no need to change! My suggestion would be to close this issue and just work within the HLS4ML repo.  Agreed?

**Comment by nhanvtran** [comment]
Yeah I think we can table this for now.  We can revisit it later if the need arises.
