### ISSUE TITLE
Other ML package interfaces?

### ISSUE THREAD

**Issue by nhanvtran** [hls-fpga-machine-learning/hls4ml#5]
TensorFlow?  How similar is it to Keras?
Caffe?

**Comment by benjaminkreis** [comment]
I think we should do TF next.  Javier gave me a TF model to try

**Comment by nhanvtran** [comment]
A prioritized list:
1. Keras/TensorFlow ✅
2. PyTorch
3. Caffe
4. MXNet

Thoughts?

**Comment by nhanvtran** [comment]
we have a better idea of what we want to do now
